server:
  enabled: false  # server is crashlooping

ingresses:
  - name: server
    ssl: true
    rules:
      - host: "knesset-mk-tracking.hasadna.org.il"
        serviceName: server
        servicePort: 80
