apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db
spec:
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: hasadna
    major: 18
  instances: 1
  storage:
    pvcTemplate:
      storageClassName: ""
      volumeMode: Filesystem
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      selector:
        matchLabels:
          app.kubernetes.io/name: hasadna-pv-knesset-mk-tracking-db
          app.kubernetes.io/managed-by: terraform-hasadna-rke2-storage
  enableSuperuserAccess: true
  superuserSecret:
    name: db-superuser
  monitoring:
    enablePodMonitor: true
