{{ if .Values.server.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  replicas: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: {{ .Values.serverImage | quote }}
        resources:
          requests:
            cpu: "25m"
            memory: "128Mi"
          limits:
            memory: "512Mi"
        env:
          - name: DB_URI
            valueFrom:
              secretKeyRef:
                name: db-app
                key: uri
{{ end }}
