cloudnative-pg:
  resources:
    requests:
      cpu: 15m
      memory: 100Mi
    limits:
      memory: 200Mi
  monitoring:
    podMonitorEnabled: true
    grafanaDashboard:
      create: true

secrets:
  - name: hasadna-postgres-superuser
    data:
      username: "~vault:Projects/k8s/cloudnative-pg-hasadna:superuser-username~"
      password: "~vault:Projects/k8s/cloudnative-pg-hasadna:superuser-password~"
