adminImage: ghcr.io/whiletrue-industries/mapathataf-admin:23b3519fd6769f6d65150bad88cebd1dd9027bae
appImage: ghcr.io/whiletrue-industries/mapathataf-app:23b3519fd6769f6d65150bad88cebd1dd9027bae
landingImage: ghcr.io/whiletrue-industries/mapathataf-landing:23b3519fd6769f6d65150bad88cebd1dd9027bae
