apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kured
spec:
  destination:
    namespace: kured
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/kured
    plugin:
      name: uumpa
    repoURL: https://github.com/hasadna/hasadna-k8s.git
    targetRevision: master
  syncPolicy:
    {{ if .Values.allowAutoSync }}
    automated:
      prune: true
      selfHeal: true
    {{ end }}
    syncOptions:
    - CreateNamespace=true
