apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hasadna-k8s-pvc-maintenance
spec:
  entrypoint: dag
  arguments:
  templates:
    - name: dag
      dag:
        tasks:
          - name: runner
            templateRef:
              name: kopia-runner
              template: script
            arguments:
              parameters:
                - name: exec_script
                  value: |
                    hasadna-k8s ceph maintenance
