apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-meirim-admin
  annotations:
    workflows.argoproj.io/rbac-rule: "'hasadna:argocd-meirim-admins' in groups"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-meirim-admin
  namespace: meirim
rules:
  - verbs: [get, list]
    apiGroups: ["argoproj.io"]
    resources: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-meirim-admin
  namespace: meirim
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-meirim-admin
subjects:
- kind: ServiceAccount
  name: argo-meirim-admin
  namespace: argo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-meirim-admin
rules:
  - verbs: [list]
    apiGroups: ["argoproj.io"]
    resources: ["workflows", "workflowtemplates", "cronworkflows"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-meirim-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-meirim-admin
subjects:
- kind: ServiceAccount
  name: argo-meirim-admin
  namespace: argo
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-meirim-admin.service-account-token
  annotations:
    kubernetes.io/service-account.name: argo-meirim-admin
type: kubernetes.io/service-account-token
