apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-global-exit-hook
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-global-exit-hook
rules:
  - verbs: [list, watch, get]
    apiGroups: ["argoproj.io"]
    resources: ["workflows", "workflowtemplates", "cronworkflows", "workflowevents"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-global-exit-hook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-global-exit-hook
subjects:
- kind: ServiceAccount
  name: argo-global-exit-hook
  namespace: argo
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-global-exit-hook.service-account-token
  annotations:
    kubernetes.io/service-account.name: argo-global-exit-hook
type: kubernetes.io/service-account-token
