apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: betaknesset-kibana
spec:
  version: 8.1.2
  podTemplate:
    spec:
      containers:
        - name: kibana
          env:
            - name: NODE_OPTIONS
              value: "--max-old-space-size=2048"
          resources:
            requests:
              memory: 512Mi
              cpu: 25m
            limits:
              memory: 1Gi
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  count: 1
  elasticsearchRef:
    name: betaknesset-elasticsearch
  config:
    server.publicBaseUrl: "https://betaknesset-kibana.hasadna.org.il"
