apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: talpihack
spec:
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ImageCatalog
    name: hasadna
    major: 18
  instances: 1
  storage:
    pvcTemplate:
      storageClassName: ""
      volumeMode: Filesystem
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 15Gi
      selector:
        matchLabels:
          app.kubernetes.io/name: hasadna-pv-cloudnative-pg-talpihack-pg-cluster
          app.kubernetes.io/managed-by: terraform-hasadna-rke2-storage
  enableSuperuserAccess: true
  superuserSecret:
    name: talpihack-postgres-superuser
  monitoring:
    enablePodMonitor: true
