enabled: true
redashImage: redash/redash:25.1.0
redashInitialize: ""

server:
  resources: {"requests": {"cpu": "25m", "memory": "256Mi"}, "limits": {"memory": "1500Mi"}}
  REDASH_WEB_WORKERS: "4"

scheduler:
  resources: {"requests": {"cpu": "25m", "memory": "128Mi"}, "limits": {"memory": "512Mi"}}

scheduledWorker:
  resources: {"requests": {"cpu": "25m", "memory": "256Mi"}, "limits": {"memory": "1500Mi"}}

worker:
  resources: {"requests": {"cpu": "50m", "memory": "256Mi"}, "limits": {"memory": "1500Mi"}}

adhocWorker:
  resources: {"requests": {"cpu": "25m", "memory": "256Mi"}, "limits": {"memory": "1500Mi"}}
  WORKERS_COUNT: 4

redis:
  resources: {"requests": {"cpu": "25m", "memory": "128Mi"}, "limits": {"memory": "512Mi"}}

postgres:
  resources: {"requests": {"cpu": "50m", "memory": "500Mi"}, "limits": {"memory": "1000Mi"}}
  nfsServer: "~iac:hasadna_nfs1_internal_ip~"
  nfsPath: "/redash/postgres"

nginx:
  resources: {"requests": {"cpu": "10m", "memory": "64Mi"}, "limits": {"memory": "256Mi"}}

ingresses:
  - name: nginx
    ssl: true
    rules:
      - host: redash.hasadna.org.il
        serviceName: nginx
        servicePort: 80

vertical_pod_autoscalers:
  - apiVersion: apps/v1
    kind: deployment
    name: adhoc-worker
  - apiVersion: apps/v1
    kind: deployment
    name: nginx
  - apiVersion: apps/v1
    kind: deployment
    name: postgres
  - apiVersion: apps/v1
    kind: deployment
    name: redis
  - apiVersion: apps/v1
    kind: deployment
    name: scheduled-worker
  - apiVersion: apps/v1
    kind: deployment
    name: scheduler
  - apiVersion: apps/v1
    kind: deployment
    name: server
