apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-controller
  namespace: argo
spec:
  template:
    spec:
      tolerations:
        - key: "HighPriorityWorkloads"
          operator: "Exists"
          effect: "NoSchedule"
