apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-server
  namespace: argo
spec:
  template:
    spec:
      tolerations:
        - key: "HighPriorityWorkloads"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: argo-server
          command: ["argo", "server", "--secure=false", "--auth-mode=sso", "--auth-mode=client"]
          readinessProbe:
            httpGet:
              scheme: HTTP
