apiVersion: v1
kind: Deployment
metadata:
  name: out-of-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: out-of-order
  template:
    metadata:
      labels:
        app: out-of-order
    spec:
      initContainers:
        - name: init
          image: python:3.12-alpine
          command:
            - python
            - -c
            - |
              import os, json
              sites = json.loads({{ .Values.outOfOrder | toJson }})
              for site in sites:
                os.makedirs(f"/var/www/{site['name']}", exist_ok=True)
                linksHtml = ""
                for link in site.get("links", []):
                  linksHtml += f'<p><a href="{link["url"]}">{link["title"]}</a></p>'
                with open(f"/var/www/{site['name']}/index.html", "w") as f:
                  f.write(f"""<!DOCTYPE html>
              <html lang="en">
                <head>
                    <meta charset="UTF-8">
                    <meta name="viewport" content="width=device-width, initial-scale=1.0">
                    <title>{site['title']}</title>
                </head>
                <body>
                    <h1>{site['title']}</h1>
                    <p>Sorry, there are some technical difficulties with this site.</p>
                    <p>Please write us at info@hasadna.org.il or see the details below if you want to help us fix it.</p>
                    <p>{site['info']}</p>
                    {linksHtml}
                    <p><img src="https://www.hasadna.org.il/wp-content/uploads/2015/11/hasadna-logo-light340.png" alt="Hasadna Logo"></p>
                </body>
              </html>
              """
              with open("/etc/nginx/conf.d/default.conf", "w") as f:
                  for site in sites:
                    f.write(f"""
              server {{
                listen 80;
                server_name {site['host']};
                root /var/www/{site['name']};
                index index.html;
                location / {{
                    try_files /index.html =404;
                }}
              }}
              """)
          volumeMounts:
            - name: confd
              mountPath: /etc/nginx/conf.d
            - name: varwww
              mountPath: /var/www
      containers:
        - name: nginx
          image: nginx:alpine
          volumeMounts:
            - name: confd
              mountPath: /etc/nginx/conf.d
            - name: varwww
              mountPath: /var/www
      volumes:
        - name: confd
          emptyDir: {}
        - name: varwww
          emptyDir: {}
